#!/usr/bin/env ruby
require 'optparse'
require 'date'
require 'time'
require 'yaml'
require 'fileutils'
require 'shellwords'

VER='0.4'

### SETUP THE COMMAND LINE OPTIONS ###############################################
options = {}
optparse = OptionParser.new do|opts|
  # Set a banner, displayed at the top
  # of the help screen.
  opts.banner = "Usage: #{__FILE__} [options]"

  # Define the options, and what they do
  options[:config] = nil
  opts.on( '-c', '--config FILE', 'Config file to use.' ) do|file|
    options[:config] = file
  end

  opts.on( '-h', '--help', 'Display this screen' ) do
    puts opts
    exit
  end

  options[:sources] = nil
  opts.on( '-s', '--sources FILE', 'Sources file to use.' ) do|file|
    options[:sources] = file
  end

  #options[:verbose] = false
  #opts.on( '-v', '--verbose', 'Output more information' ) do
  #  options[:verbose] = true
  #end
end

optparse.parse!

#VERBOSE = options[:verbose]
CONFIG = options[:config] ? options[:config] : File.dirname(__FILE__)+"/config.yml"
SOURCES = options[:sources] ? options[:sources] : File.dirname(__FILE__)+"/sources.yml"

#############################################################################################

raise "Config file: `#{CONFIG}' could not be found" unless File.exist? CONFIG
raise "Sources file: `#{SOURCES}' could not be found" unless File.exist? SOURCES

cfg = YAML.load_file(CONFIG)
@sources = YAML.load_file(SOURCES)
@dest_device_uuid = cfg['dest_device_uuid']
@dest_subfolder = cfg['dest_subfolder']
@mount_dest_device = cfg['mount_dest_device'].nil? ? true : cfg['mount_dest_device']
@backup_mount_point = cfg['backup_mount_point']
@log_file = cfg['log_file'].gsub("%d",Time.now.strftime("%Y%m%d_%H%M%S"))
@device = `blkid | grep '#{cfg['dest_device_uuid']}'`.split(':').first

def no_trailing_slash(str)
  str ||= ''
  str.sub(/(\/)+$/, '')
end

def backup_path
  @dest_subfolder = no_trailing_slash(@dest_subfolder)
  @backup_path ||=
  if @dest_subfolder.empty?
    @backup_mount_point
  else
    File.join(@backup_mount_point, @dest_subfolder)
  end
end

@snapshot_dir = "#{backup_path}/snapshots"
@snapshot_max_age = cfg['snapshot_max_age']
@lock_file = cfg['lock_file']
@hostname = `hostname -s`.strip
@email = cfg['alert_email'] || nil


@rsync_options = cfg['rsync_options']
@mount_options = cfg['mount_options']
@deduplicate = cfg['deduplicate']

@alerts = [] # an empty array to store alerts that will be emailed

def lock
  if locked?
    message = "It seems another backup is still running, or previous backup did not complete.  If you are sure that there are no backups currently running then try deleting the lockfile at `#{@lock_file}'."

    alert message
    send_alerts
    exit 1
  end
  FileUtils.touch @lock_file
end

def unlock
  FileUtils.rm @lock_file
end

def locked?
  File.exist? @lock_file
end

def log(message)
  date = Time.now.asctime

  message.each_line do |line|
    log = File.open(@log_file, 'a')
    log.puts "#{date} BTRFS Time Machine: #{message}"
    log.close
  end
end

def alert(message)
  log(message)
  @alerts.push message
end

def alert_and_abort(message)
  alert("#{message}")
  alert("Backup aborting due to fatal error")
  send_alerts
  exit 1
end

def send_alerts
  return 0 if @email.nil? || @alerts.count == 0

  subject = "BTRFS Time Machine failed on #{@hostname}"
  message = ''

  @alerts.each do |alert|
    message += "* #{alert}\n"
  end

  message += "\nFor more details check the log file at '#{@hostname}:#{@log_file}'."

  `echo #{message.shellescape} | mail -s "#{subject}" #{@email}`
end

def mount(device,mount_point)
  alert_and_abort "You did not provide me with a device and mount point." unless device && mount_point
  unless is_mounted?(device,mount_point) then
    log "Mounting #{device} to #{mount_point}"
    `sudo mount #{device} #{mount_point}`
  end
  alert_and_abort "Could not mount #{@device} to #{@backup_mount_point}" unless $?.success?
  $?.success?
end

def remount_as(option,device,mount_point)
  alert_and_abort "I don't have a mount option, device and mount point." unless option && device && mount_point
  alert_and_abort "Cannot remount because #{mount_point} is not mounted" unless is_mounted?(device,mount_point)
  log "Remounting #{mount_point} as #{option}"

  mount_opts = ['remount']
  mount_opts.push(@mount_options) unless @mount_options.nil?
  mount_opt_str = mount_opts.join(',')

  `sudo mount -o #{mount_opt_str},#{option} #{device} #{mount_point}`
  alert_and_abort "mount #{device} as #{option} failed" unless $?.success?
  $?.success?
end

def is_mounted?(device,mount_point)
  alert_and_abort "is_mounted says: You did not provide me with a device and mount point." unless device && mount_point
  found = false
  File.open('/proc/mounts', 'r').each_line do |line|
    found = true if line.include? mount_point
  end
  found
end

def command_path(command)
  cmd_path=`which #{command}`.strip
  alert_and_abort "#{command}: command not found" if cmd_path.empty?
  cmd_path
end

def rsync
  @sources.each do |src_data|
    src = src_data['source']
    dst = File.expand_path("#{backup_path}/latest/#{src == '/' ? 'root' : src}")
    # XXX Consider an explicit enum, with btrfs, lvm and dm-thin snapshots.
    if src_data['snapshot']
      do_snapshot_src = true
      src2 = File.join(src, "ro-snapshot")
      if File.exist? src2
        alert_and_abort "read-only source snapshot already exists at #{src2}"
      end
      `sudo btrfs subvolume snapshot -r #{src} #{src2}`
      alert_and_abort "Failed to snapshot `#{src}'" unless $?.success?
    else
      do_snapshot_src = false
      src2 = src
    end
    rsync = command_path('rsync')
    rsync_opts = '-v -aAX --numeric-ids --delete --delete-excluded --human-readable --inplace --no-whole-file'

    unless @rsync_options.nil?
      rsync_opts += ' ' + @rsync_options.join(' ')
    end

    unless src_data['rsync_options'].nil?
      rsync_opts += ' ' + src_data['rsync_options'].join(' ')
    end

    if src_data.fetch('snapshot', false) or src_data.fetch('one-filesystem', false)
      rsync_opts += ' -x'
    end

    if src_data.key? 'inclusions'
      src_data['inclusions'].each do |inclusion|
        inclusion.gsub!(/^\.\//, '')                  # drop off the ./ because rsync doesn't like em.
        rsync_opts += " --include '#{inclusion}'"
      end
    end

    if src_data.key? 'exclusions' then
      src_data['exclusions'].each do |exclusion|
        exclusion.gsub!(/^\.\//, '')                  # drop off the ./ because rsync doesn't like em.
        rsync_opts += " --exclude '#{exclusion}'"
      end
    end

    alert_and_abort "rsync says: I need a source and destination" unless src && dst
    alert_and_abort "Could not create #{dst} directory" unless FileUtils.mkdir_p dst

    # start the backup
    log "Starting the backup:"
    rsync_cmd="sudo #{rsync} #{rsync_opts} #{no_trailing_slash(src2)}/ #{dst} >> #{@log_file} 2>&1" # src needs a trailing slash on dir or it'll go in wrong dir.
    log "Running '#{rsync_cmd}'"
    `#{rsync_cmd}`
    rsync_failed = ! $?.success?
    if do_snapshot_src and src != src2
      `sudo btrfs subvolume delete #{src2}`
      alert "Failed to clean up `#{src2}'" unless $?.success?
    end
    alert_and_abort "Failed to backup `#{src}'" if rsync_failed
  end
end

def btrfs_scan
  `sudo btrfs device scan >> #{@log_file} 2>&1`
end

def btrfs_volume?(path)
  unless File.directory? path
    return false
  end

  return true if File.stat(path).ino == 256
  false
end

def btrfs_snapshot
  date = Time.now.strftime("%Y-%m-%d %H:%M:%S")
  FileUtils.mkdir_p @snapshot_dir

  log "Creating file system snapshot."
  alert_and_abort "A snapshot by that name already exists" if File.directory?("#{@snapshot_dir}/#{date}")
  `sudo btrfs subvolume snapshot -r #{backup_path}/latest '#{@snapshot_dir}/#{date}' >> #{@log_file} 2>&1`        # TODO: make logging better
  $?.success?
end

def btrfs_delete_snapshot(date)
  log "deleting snapshot from #{date}"
  `sudo btrfs subvolume delete '#{@snapshot_dir}/#{date}' >> #{@log_file} 2>&1`
end

def btrfs_snapshot_rotate
  snapshots = Dir.entries(@snapshot_dir)
  snapshots.delete ".."
  snapshots.delete "."

  snapshots.each do |snapshot|
    btrfs_delete_snapshot snapshot if Time.parse(snapshot) < Time.now - (@snapshot_max_age * 3600)
  end
end

lock
at_exit do
  unlock
end
log "BTRFS time machine version #{VER} started."
btrfs_scan

# mount the backup filesystem
mount @device, @backup_mount_point if @mount_dest_device

# backup filesystem needs to be btrfs for snapshots.
path = File.join(backup_path, "latest")
unless btrfs_volume? path
  alert_and_abort "Subvolume was not found at `#{path}'. Try running `btrfs subvolume create #{path}'."
end

remount_as "rw", @device, @backup_mount_point if @mount_dest_device

rsync

if @deduplicate
  log "Will dedup"
  `sudo bedup dedup --flush -- #{backup_path}/latest >> #{@log_file} 2>&1`
  alert_and_abort "Could not deduplicate" unless $?.success?
else
  log "dedup not enabled"
end

btrfs_snapshot
btrfs_snapshot_rotate
remount_as "ro", @device, @backup_mount_point if @mount_dest_device

log "Finished Successfully!"
send_alerts
